services:
  db:
    image: 'postgres:13.7'
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
      
    volumes:
    - my_app_users_data:/var/lib/postgresql/data/ 
    - ./database_scripts/:/docker-entrypoint-initdb.d/
  
  pgadmin:
    image: dpage/pgadmin4:8.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL : "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD : "admin"
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  my_app_users_data: # named volumes can be managed easier using docker-compose